Vidly/Controllers/Api/CustomersController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Http;
using AutoMapper;
using Vidly.DTOS;
using Vidly.Models;

namespace Vidly.Controllers.Api
{
    public class CustomersController : ApiController
    {
        private readonly ApplicationDbContext _context;

        public CustomersController ()
        {
            _context = new ApplicationDbContext();
        }


        // GET /api/customers
        public IHttpActionResult GetCustomers () =>
            Ok( _context.Customers
                .Include( c => c.MembershipType )
                .ToList()
                .Select( Mapper.Map<Customer , CustomerDTO> ) );




        //GET /api/customers/1
        public IHttpActionResult GetCustomer ( int id )
        {
            Customer customer = _context.Customers
                .Include( c => c.MembershipType )
                .SingleOrDefault( c => c.Id == id );


            if ( customer == null )
            {
                return NotFound();
            }

            return Ok( Mapper.Map<Customer , CustomerDTO>( customer ) );
        }

        //POST /api/customers
        [HttpPost]
        public IHttpActionResult CreateCustomer ( CustomerDTO customerDTO )
        {
            if ( !ModelState.IsValid )
            {
                return BadRequest();
            }

            var customer = Mapper.Map<CustomerDTO , Customer>( customerDTO );
            _context.Customers.Add( customer );
            _context.SaveChanges();

            customerDTO.Id = customer.Id;

            return Created( new Uri( Request.RequestUri + "/" + customer.Id ) , customerDTO );

        }

        // PUT /api/customers/1
        [HttpPut]
        public IHttpActionResult UpdateCustomer ( int id , CustomerDTO customerDTO )
        {
            if ( !ModelState.IsValid )
            {
                return BadRequest();
            }

            var customerInDb = _context.Customers.SingleOrDefault( c => c.Id == id );

            if ( customerInDb == null )
            {
                return NotFound();
            }

            Mapper.Map( customerDTO , customerInDb );

            _context.SaveChanges();

            return Ok();
        }

        //DELETE /api/customer
        [HttpDelete]
        public IHttpActionResult DeleteCustomer ( int id )
        {
            var customerInDb = _context.Customers.SingleOrDefault( c => c.Id == id );

            if ( customerInDb == null )
            {
                return NotFound();
            }

            _context.Customers.Remove( customerInDb );
            _context.SaveChanges();

            return Ok();
        }
    }
}

Vidly/Controllers/Api/MoviesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Http;
using AutoMapper;
using Vidly.DTOS;
using Vidly.Interfaces;
using Vidly.Models;

namespace Vidly.Controllers.Api
{
    public class MoviesController : ApiController, IMoviesController
    {
        private readonly ApplicationDbContext _context;

        public MoviesController ()
        {
            _context = new ApplicationDbContext();
        }

        public IHttpActionResult GetMovies () =>
            Ok( _context.Movies
                .Include( g => g.Genre )
                .ToList()
                .Select( Mapper.Map<Movie , MovieDTO> ) );

        public IHttpActionResult GetMovie ( int id )
        {
            var movie = _context.Movies
                .Include( g => g.Genre )
                .SingleOrDefault( c => c.Id == id );

            if ( movie == null )
            {
                return NotFound();
            }

            return Ok( Mapper.Map<Movie , MovieDTO>( movie ) );
        }

        [HttpPut]
        public IHttpActionResult UpdateMovie ( int id , MovieDTO movieDto )
        {
            if ( !ModelState.IsValid )
            {
                return BadRequest();
            }

            var movieInDb = _context.Movies.SingleOrDefault( m => m.Id == id );

            if ( movieInDb == null )
            {
                return NotFound();
            }

            Mapper.Map( movieDto , movieInDb );

            _context.SaveChanges();

            return Ok();
        }

        [HttpDelete]
        public IHttpActionResult Deletemovie ( int id )
        {
            if ( !ModelState.IsValid )
            {
                return BadRequest();
            }

            var movieInDb = _context.Movies.SingleOrDefault( m => m.Id == id );

            if ( movieInDb == null )
            {
                return NotFound();
            }

            _context.Movies.Remove( movieInDb );
            _context.SaveChanges();

            return Ok();
        }

        [HttpPost]
        public IHttpActionResult CreateMovie ( MovieDTO movieDto )
        {
            if ( !ModelState.IsValid )
            {
                return BadRequest();
            }

            var movie = Mapper.Map<MovieDTO , Movie>( movieDto );

            _context.Movies.Add( movie );
            _context.SaveChanges();

            movieDto.Id = movie.Id;

            return Created( new Uri( Request.RequestUri + "/" + movie.Id ) , movieDto );
        }
    }
}

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
@Html.Partial("_NavBar")
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Applicazione ASP.NET</p>
    </footer>
</div>

@Scripts.Render("~/bundles/lib")
@RenderSection("scripts", required: false)
</body>
</html>

Vidly/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink( "Vidly" , "Index" , "Home" , new { area = "" } , new { @class = "navbar-brand" } )
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink( "Customer" , "Index" , "Customers" )</li>
                <li>@Html.ActionLink( "Movie" , "Index" , "Movies" )</li>
            </ul>
            @Html.Partial( "_LoginPartial" )
        </div>
    </div>
</div>